# Generated by Django 3.0.8 on 2020-07-08 09:02

import core.utils
from django.db import migrations, models
import exiffield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('image', core.utils.CustomImageField(upload_to='user_img')),
                ('exif', exiffield.fields.ExifField(default={}, editable=False)),
                ('checksums', models.CharField(max_length=256, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
